apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: production
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 6
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: alexkainzinger/jku-cloud-native-node-app:production-20221220-2030
          ports:
            - containerPort: 8081
